### ISSUE TITLE
Dead link. Impossible to download shortcut.

### ISSUE THREAD

**Issue by pulssart** [nicolodiamante/dispatch#1]
Dead link. Impossible to download shortcut.

**Comment by nicolodiamante** [comment]
Hi @pulssart , 

It appears that there is an issue with Apple. Upon checking all my other links, none of them seem to be available. This problem has occurred before, and it was resolved on its own after a few hours. 

In case you need it, here is a new link to download "[Dispatch](https://www.icloud.com/shortcuts/5e1e07471fce45a1ba44d1e2128cee5f)". 

Please inform me if the problem persists.
